In [ ]:
#FIND-S

import numpy as np
import pandas as pd

In [ ]:
print("The given data is:")
data = pd.read_csv("EnjoySport.csv")
data

The given data is:

     Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1  Sunny    Warm     High  Strong  Warm     Same        Yes
2  Rainy    Cold     High  Strong  Warm   Change         No
3  Sunny    Warm     High  Strong  Cool   Change        Yes

In [ ]:
def FindS(data):
    dt = np.array(data)
    n = len(dt[0])-1
    target = np.array(data)[:,-1]
    specific_hypothesis=["_"]*n
    print("H0 = ",specific_hypothesis)
    hypothesis = []
    for i, val in enumerate(target): 
        if val == 'Yes': 
            specific_hypothesis=dt[i][:-1].copy()
            hypothesis.append(specific_hypothesis)
            break
    for i, val in enumerate(dt): 
        
        if target[i] =='Yes': 
            for x in range(n): 
                if val[x] != specific_hypothesis[x]: 
                    specific_hypothesis[x]='?'
                else: 
                    pass
        hypothesis.append(specific_hypothesis)
        print("H"+str(i+1)+" = ",specific_hypothesis)
    
    print("\nThe maximally specific hypothesis is:\n", specific_hypothesis)
    return

In [ ]:
FindS(data)

H0 =  ['_', '_', '_', '_', '_', '_']
H1 =  ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
H2 =  ['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']
H3 =  ['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']
H4 =  ['Sunny' 'Warm' '?' 'Strong' '?' '?']

The maximally specific hypothesis is:
 ['Sunny' 'Warm' '?' 'Strong' '?' '?']